# general settings
name: train_HAT_thermalSRx8_48_cutblur_fineturn
model_type: aug_HATModel
scale: 8
num_gpu: 2
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: thermal_image
    type: aug_paired_dataset
    dataroot_gt: datasets/dataset_CIDIS_sisr_x8/thermal/train/GT_sub_54
    dataroot_lq: datasets/dataset_CIDIS_sisr_x8/thermal/train/LR_x8_sub_54
    meta_info_file: hat/data/meta_info/meta_info_train_GT_sub_54.txt
    io_backend:
      type: disk

    gt_size: 384
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: thermal_image
    type: PairedImageDataset
    dataroot_gt: datasets/dataset_CIDIS_sisr_x8/thermal/val/GT/
    dataroot_lq: datasets/dataset_CIDIS_sisr_x8/thermal/val/LR_x8/
    io_backend:
      type: disk

# network structures
network_g:
  type: aug_HAT
  upscale: 8
  in_chans: 192
  img_size: 48
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ./experiments/pretrained/df2k_pretrained.pth
  strict_load_g: true
  resume_state: ~

# DA
augs : ["cutblur"]
prob : [1.0]
alpha : [0.7]
aux_prob : 1.0
aux_alpha : 1.2

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [25000, 40000, 45000, 47500]
    gamma: 0.5

  total_iter: 50000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e2
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 8
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 8
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
